version: '3'
services:
  node-app:
    build: .
    container_name: store-api-node
    restart: always
    environment:
      - APP_PORT=8000
      - APP_HOST=localhost
      - DB_URL=mongodb://<USERNAME>:hello123@database:27017/store-api?authSource=admin
      - DEBUG_MODE=true
      - NODE_ENV=development
      - SECRET_KEY=ipfhUCFRZ4fce7GWaatUZMQbQ655sygRq0KUATOUX4VB1RFjaUtl6lfKmlP4AHg8
      - REFRESH_KEY=ipfhUCFRZ4fce7GWaatUZMQbQ655sygRq0KUATOUX4VB1RFjaUtl6lfKmlP4AHg8
    ports:
      - "8000:8000"
    expose:
      - 8000
    command: [ "node", "dist/app.js" ]
    networks:
      - store-api_store-network
networks:
  store-api_store-network:
    external: true
