version: '3'
services:
  node-app:
    build: .
    container_name: store-api
    restart: always
    environment:
      - APP_PORT=8000
      - APP_HOST=localhost
      - DB_URL=mongodb://root:hello123@database:27017/store-api?authSource=admin
      - DEBUG_MODE=true
      - NODE_ENV=development
      - SECRET_KEY=!rad9TN`&B{!pg&Y($oTwOhYfEJ4{0sEBYtu]xqa2^8,Iyc^8HP[[XB,J$O)~BL
      - REFRESH_KEY=hOS1|4NM.P#F^BA]JiIX^B0AS@JY+E20Zphjs2ER[}FMJXq3}1vH~iGrQPqtycv
    expose:
      - 8000
    command: ["node", "src/app.js"]
    depends_on:
      - database
  database:
    container_name: store-database
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: hello123
    image: mongo
    volumes:
      - mongo-db:/data/db
  webserver:  
    container_name: store-webserver
    image: nginx:1.21.5-alpine
    ports:
      - "80:80"
      - "443:443"
    restart: always
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
    depends_on:
      - node-app
  certbot:
    image: certbot/certbot
    container_name: store-certbot
    volumes:
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
    depends_on:
      - webserver
    command: certonly --standalone --preferred-challenges http --email storerestapi@gmail.com --agree-tos --no-eff-email --staging -d test.storerestapi.com
volumes:
  mongo-db:
  certbot-etc:
  certbot-var: