# *** This Dockefile is generated by KloverCloud. You can modify it based on your application requirements *** #

FROM container-registry.console.klovercloud.com/klovercloud/node:13-slim

RUN useradd -ms /bin/bash klovercloud

WORKDIR /home/klovercloud

COPY package*.json ./

RUN npm install
COPY . .


EXPOSE 8000

EXPOSE 8081


USER klovercloud
CMD [ "npm", "start" ]


