version: '3'
services:
  node-app:
    build: .
    # ports:
    #   - 8000:8000
    container_name: store-api
    restart: always
    environment:
      - APP_PORT=8000
      - APP_HOST=localhost
      - DB_URL=mongodb://root:hello123@mongo:27017/store-api?authSource=admin
      - DEBUG_MODE=true
      - NODE_ENV=development
      - SECRET_KEY=!rad9TN`&B{!pg&Y($oTwOhYfEJ4{0sEBYtu]xqa2^8,Iyc^8HP[[XB,J$O)~BL
      - REFRESH_KEY=hOS1|4NM.P#F^BA]JiIX^B0AS@JY+E20Zphjs2ER[}FMJXq3}1vH~iGrQPqtycv
    expose:
      - 8000
    command: ["node", "src/app.js"]
    depends_on:
      - mongo
  mongo:
    container_name: store-mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: hello123
    image: mongo
    volumes:
      - mongo-db:/data/db
  nginx:
    container_name: store-nginx
    image: nginx:1.21.5-alpine
    ports:
      - "8000:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - node-app
volumes:
  mongo-db: