version: '3'
services:
  node-app:
    image: storerestapi/store-api-node:latest
    container_name: store-api-node
    restart: always
    environment:
      - APP_PORT=8000
      - APP_HOST=localhost
      - DB_URL=mongodb://root:gCrm4Q8V8e@database:27017/store-api?authSource=admin
      - DEBUG_MODE=true
      - NODE_ENV=development
      - SECRET_KEY=!rad9TN`&B{!pg&Y($oTwOhYfEJ4{0sEBYtu]xqa2^8,Iyc^8HP[[XB,J$O)~BL
      - REFRESH_KEY=hOS1|4NM.P#F^BA]JiIX^B0AS@JY+E20Zphjs2ER[}FMJXq3}1vH~iGrQPqtycv
    ports:
      - "8000:8000"
    expose:
      - 8000
    command: [ "node", "dist/app.js" ]
    networks:
      - store-api_store-network
networks:
  store-api_store-network:
    external: true
