version: '3'
services:
  node-app:
    build: .
    container_name: store-api
    restart: always
    environment:
      - APP_PORT=${APP_PORT}
      - APP_HOST=${APP_HOST}
      - DB_URL=${APP_HOST}
      - DEBUG_MODE=${DEBUG_MODE}
      - NODE_ENV=${NODE_ENV}
      - SECRET_KEY=${SECRET_KEY}
      - REFRESH_KEY=${REFRESH_KEY}
    ports:
      - "8000:8000"
    expose:
      - 8000
    command: [ "node", "dist/app.js" ]
    depends_on:
      - database
    networks:
      - store-network
networks:
  store-network:
    external: true
