# For more information see: https://docs.docker.com/build/ci/github-actions/multi-platform/

name: Testcase

on:
  push:
    branches: [ "master" ]

jobs:
  Build-App:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.20.x]

    steps:
    - name: Checkout
      uses: actions/checkout@v3
    
    - name: Use node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - name: Install packages
      run: npm ci

    - name: Run testcase
      run: npm test